<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JXwJF7wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JXwJF7w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JXwJF7w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tank' => ['privates', '.errored..service_locator.JXwJF7w.App\\Entity\\Tank', NULL, 'Cannot autowire service ".service_locator.JXwJF7w": it needs an instance of "App\\Entity\\Tank" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tank' => 'App\\Entity\\Tank',
        ]);
    }
}
