<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CdQ8OBmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cdQ8OBm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cdQ8OBm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tankCheckDetail' => ['privates', '.errored..service_locator.cdQ8OBm.App\\Entity\\TankCheckDetail', NULL, 'Cannot autowire service ".service_locator.cdQ8OBm": it needs an instance of "App\\Entity\\TankCheckDetail" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'tankCheckDetail' => 'App\\Entity\\TankCheckDetail',
        ]);
    }
}
