<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QtMre8rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qtMre8r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qtMre8r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tankCheckArticle' => ['privates', '.errored..service_locator.qtMre8r.App\\Entity\\TankCheckArticle', NULL, 'Cannot autowire service ".service_locator.qtMre8r": it needs an instance of "App\\Entity\\TankCheckArticle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'tankCheckArticle' => 'App\\Entity\\TankCheckArticle',
        ]);
    }
}
