<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCyJ2hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RCy_J2h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RCy_J2h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'instructor' => ['privates', '.errored..service_locator.RCy_J2h.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.RCy_J2h": it needs an instance of "App\\Entity\\Member" but this type has been excluded in "config/services.yaml".'],
        ], [
            'instructor' => 'App\\Entity\\Member',
        ]);
    }
}
