<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TePp8oXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tePp8oX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tePp8oX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'vendor' => ['privates', '.errored..service_locator.tePp8oX.App\\Entity\\Vendor', NULL, 'Cannot autowire service ".service_locator.tePp8oX": it needs an instance of "App\\Entity\\Vendor" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'vendor' => 'App\\Entity\\Vendor',
        ]);
    }
}
