<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4MTMdDBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4MTMdDB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4MTMdDB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.4MTMdDB.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.4MTMdDB": it needs an instance of "App\\Entity\\Booking" but this type has been excluded in "config/services.yaml".'],
        ], [
            'booking' => 'App\\Entity\\Booking',
        ]);
    }
}
