<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RacGmwFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RacGmwF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RacGmwF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.RacGmwF.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.RacGmwF": it needs an instance of "App\\Entity\\Booking" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'scheduleRepository' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
        ], [
            'booking' => 'App\\Entity\\Booking',
            'entityManager' => '?',
            'scheduleRepository' => 'App\\Repository\\ScheduleRepository',
        ]);
    }
}
