<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cf1wKsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Cf1wKs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Cf1wKs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tankRepository' => ['privates', 'App\\Repository\\TankRepository', 'getTankRepositoryService', true],
        ], [
            'tankRepository' => 'App\\Repository\\TankRepository',
        ]);
    }
}
