<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NkKzOAmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nkKzOAm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nkKzOAm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'schedule' => ['privates', '.errored..service_locator.nkKzOAm.App\\Entity\\Schedule', NULL, 'Cannot autowire service ".service_locator.nkKzOAm": it needs an instance of "App\\Entity\\Schedule" but this type has been excluded in "config/services.yaml".'],
            'student' => ['privates', '.errored..service_locator.nkKzOAm.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.nkKzOAm": it needs an instance of "App\\Entity\\Member" but this type has been excluded in "config/services.yaml".'],
        ], [
            'schedule' => 'App\\Entity\\Schedule',
            'student' => 'App\\Entity\\Member',
        ]);
    }
}
