<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_InR_60ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.inR.60Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.inR.60Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'schedule' => ['privates', '.errored..service_locator.inR.60Z.App\\Entity\\Schedule', NULL, 'Cannot autowire service ".service_locator.inR.60Z": it needs an instance of "App\\Entity\\Schedule" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'schedule' => 'App\\Entity\\Schedule',
        ]);
    }
}
