<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrevetsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BrevetsType' shared autowired service.
     *
     * @return \App\Form\BrevetsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BrevetsType.php';

        return $container->privates['App\\Form\\BrevetsType'] = new \App\Form\BrevetsType();
    }
}
