<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMember3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RCy_J2h.App\Entity\Member' shared service.
     *
     * @return \App\Entity\Member
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RCy_J2h": it needs an instance of "App\\Entity\\Member" but this type has been excluded in "config/services.yaml".');
    }
}
