<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchedule2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.inR.60Z.App\Entity\Schedule' shared service.
     *
     * @return \App\Entity\Schedule
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.inR.60Z": it needs an instance of "App\\Entity\\Schedule" but this type has been excluded in "config/services.yaml".');
    }
}
