<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTankCheckArticleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.B9GuWkD.App\Entity\TankCheckArticle' shared service.
     *
     * @return \App\Entity\TankCheckArticle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.B9GuWkD": it needs an instance of "App\\Entity\\TankCheckArticle" but this type has been excluded in "config/services.yaml".');
    }
}
