<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTankService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G2W1AMC.App\Entity\Tank' shared service.
     *
     * @return \App\Entity\Tank
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.G2W1AMC": it needs an instance of "App\\Entity\\Tank" but this type has been excluded in "config/services.yaml".');
    }
}
