<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTankCheck2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yQJ44Bq.App\Entity\TankCheck' shared service.
     *
     * @return \App\Entity\TankCheck
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yQJ44Bq": it needs an instance of "App\\Entity\\TankCheck" but this type has been excluded in "config/services.yaml".');
    }
}
