<?php

namespace ContainerLZp7KxF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVendor2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tePp8oX.App\Entity\Vendor' shared service.
     *
     * @return \App\Entity\Vendor
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tePp8oX": it needs an instance of "App\\Entity\\Vendor" but this type has been excluded in "config/services.yaml".');
    }
}
