<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vendor extends \App\Entity\Vendor implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'postal' => [parent::class, 'postal', null],
        "\0".parent::class."\0".'street' => [parent::class, 'street', null],
        "\0".parent::class."\0".'tankChecks' => [parent::class, 'tankChecks', null],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null],
        'city' => [parent::class, 'city', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'notes' => [parent::class, 'notes', null],
        'phone' => [parent::class, 'phone', null],
        'postal' => [parent::class, 'postal', null],
        'street' => [parent::class, 'street', null],
        'tankChecks' => [parent::class, 'tankChecks', null],
        'website' => [parent::class, 'website', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
