<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TankCheck extends \App\Entity\TankCheck implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'articles' => [parent::class, 'articles', null],
        "\0".parent::class."\0".'checkDate' => [parent::class, 'checkDate', null],
        "\0".parent::class."\0".'costInformation' => [parent::class, 'costInformation', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'tank' => [parent::class, 'tank', null],
        "\0".parent::class."\0".'vendor' => [parent::class, 'vendor', null],
        "\0".parent::class."\0".'vendorName' => [parent::class, 'vendorName', null],
        'articles' => [parent::class, 'articles', null],
        'checkDate' => [parent::class, 'checkDate', null],
        'costInformation' => [parent::class, 'costInformation', null],
        'id' => [parent::class, 'id', null],
        'notes' => [parent::class, 'notes', null],
        'tank' => [parent::class, 'tank', null],
        'vendor' => [parent::class, 'vendor', null],
        'vendorName' => [parent::class, 'vendorName', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
