<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXc1r2SO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXc1r2SO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXc1r2SO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXc1r2SO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXc1r2SO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xc1r2SO',
    'container.build_id' => 'f02947b9',
    'container.build_time' => 1791634447,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXc1r2SO');
