<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUAVKv25\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUAVKv25/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUAVKv25.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUAVKv25\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUAVKv25\App_KernelDevDebugContainer([
    'container.build_hash' => 'UAVKv25',
    'container.build_id' => '58f7509e',
    'container.build_time' => 1791634887,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUAVKv25');
