<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK8G3I9h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK8G3I9h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK8G3I9h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK8G3I9h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK8G3I9h\App_KernelDevDebugContainer([
    'container.build_hash' => 'K8G3I9h',
    'container.build_id' => 'd8d5ade2',
    'container.build_time' => 1724596806,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK8G3I9h');
