<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0aQAitBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0aQAitB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0aQAitB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tankCheckRepository' => ['privates', 'App\\Repository\\TankCheckRepository', 'getTankCheckRepositoryService', true],
        ], [
            'tankCheckRepository' => 'App\\Repository\\TankCheckRepository',
        ]);
    }
}
