<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EwSAumaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EwSAuma' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EwSAuma'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'course' => ['privates', '.errored..service_locator.EwSAuma.App\\Entity\\Courses', NULL, 'Cannot autowire service ".service_locator.EwSAuma": it needs an instance of "App\\Entity\\Courses" but this type has been excluded in "config/services.yaml".'],
            'scheduleRepository' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
        ], [
            'course' => 'App\\Entity\\Courses',
            'scheduleRepository' => 'App\\Repository\\ScheduleRepository',
        ]);
    }
}
