<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SfpVTkJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sfpVTkJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sfpVTkJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tankCheckDetailRepository' => ['privates', 'App\\Repository\\TankCheckDetailRepository', 'getTankCheckDetailRepositoryService', true],
        ], [
            'tankCheckDetailRepository' => 'App\\Repository\\TankCheckDetailRepository',
        ]);
    }
}
