<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3AFEbSYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3AFEbSY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3AFEbSY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booking' => ['privates', '.errored..service_locator.3AFEbSY.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.3AFEbSY": it needs an instance of "App\\Entity\\Booking" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'booking' => 'App\\Entity\\Booking',
            'entityManager' => '?',
        ]);
    }
}
