<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SSU52HdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SSU52Hd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SSU52Hd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'brevet' => ['privates', '.errored..service_locator.SSU52Hd.App\\Entity\\Brevets', NULL, 'Cannot autowire service ".service_locator.SSU52Hd": it needs an instance of "App\\Entity\\Brevets" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'brevet' => 'App\\Entity\\Brevets',
            'entityManager' => '?',
        ]);
    }
}
