<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YQJ44BqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yQJ44Bq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yQJ44Bq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'checkArticleRepository' => ['privates', 'App\\Repository\\TankCheckArticleRepository', 'getTankCheckArticleRepositoryService', true],
            'tankCheck' => ['privates', '.errored..service_locator.yQJ44Bq.App\\Entity\\TankCheck', NULL, 'Cannot autowire service ".service_locator.yQJ44Bq": it needs an instance of "App\\Entity\\TankCheck" but this type has been excluded in "config/services.yaml".'],
        ], [
            'checkArticleRepository' => 'App\\Repository\\TankCheckArticleRepository',
            'tankCheck' => 'App\\Entity\\TankCheck',
        ]);
    }
}
