<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bu1OL42Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bu1OL42' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bu1OL42'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'student' => ['privates', '.errored..service_locator.bu1OL42.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.bu1OL42": it needs an instance of "App\\Entity\\Member" but this type has been excluded in "config/services.yaml".'],
        ], [
            'student' => 'App\\Entity\\Member',
        ]);
    }
}
