<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V0J5T2hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V0J5T2h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V0J5T2h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tankCheckDetail' => ['privates', '.errored..service_locator.V0J5T2h.App\\Entity\\TankCheckDetail', NULL, 'Cannot autowire service ".service_locator.V0J5T2h": it needs an instance of "App\\Entity\\TankCheckDetail" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tankCheckDetail' => 'App\\Entity\\TankCheckDetail',
        ]);
    }
}
