<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LkIft9VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lkIft9V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lkIft9V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'instructor' => ['privates', '.errored..service_locator.lkIft9V.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.lkIft9V": it needs an instance of "App\\Entity\\Member" but this type has been excluded in "config/services.yaml".'],
            'passwordEncoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'entityManager' => '?',
            'instructor' => 'App\\Entity\\Member',
            'passwordEncoder' => '?',
        ]);
    }
}
