<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XGj_YbnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XGj.Ybn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XGj.Ybn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'schedule' => ['privates', '.errored..service_locator.XGj.Ybn.App\\Entity\\Schedule', NULL, 'Cannot autowire service ".service_locator.XGj.Ybn": it needs an instance of "App\\Entity\\Schedule" but this type has been excluded in "config/services.yaml".'],
            'user' => ['privates', '.errored..service_locator.XGj.Ybn.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.XGj.Ybn": it needs an instance of "App\\Entity\\Member" but this type has been excluded in "config/services.yaml".'],
        ], [
            'schedule' => 'App\\Entity\\Schedule',
            'user' => 'App\\Entity\\Member',
        ]);
    }
}
