<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LXAS3kiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LXAS3ki' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LXAS3ki'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'brevetsRepository' => ['privates', 'App\\Repository\\BrevetsRepository', 'getBrevetsRepositoryService', true],
        ], [
            'brevetsRepository' => 'App\\Repository\\BrevetsRepository',
        ]);
    }
}
