<?php

namespace Container9x8heHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrevets2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kMtqRgS.App\Entity\Brevets' shared service.
     *
     * @return \App\Entity\Brevets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kMtqRgS": it needs an instance of "App\\Entity\\Brevets" but this type has been excluded in "config/services.yaml".');
    }
}
